from __future__ import annotations

from engines.base import (
    GenericCorrectionEngine,
    apply_replacements,
    clean_document_text,
    repair_missing_drop_capital,
    split_glued_uppercase_words,
)
from engines.registry import register_engine

# Artefactos tipicos de columnas / periodismo politico mexicanos.
PERIODISMO_REPLACEMENTS: dict[str, str] = {
    "Canadá(T-MEC)": "Canadá (T-MEC)",
    "Borderlands(editorial": "Borderlands (editorial",
    'Harfuch"y': 'Harfuch" y',
    'en"sombras': 'en "sombras',
    'muerte"y': 'muerte" y',
    'que"no': 'que "no',
    "lafrontera": "la frontera",
    "ellado": "el lado",
    "porlaembajada": "por la embajada",
    "EUdurante": "EU durante",
    "laadministración": "la administración",
    "losmismosjesuitas": "los mismos jesuitas",
    "mismosjesuitas": "mismos jesuitas",
    "esefuturo": "ese futuro",
    "migratoriasy": "migratorias y",
    "migración seguridad": "migración y seguridad",
    "Brownsville Matamoros": "Brownsville y Matamoros",
    "cercanosa": "cercanos a",
    "contactadoa": "contactado a",
    'Paca"y': 'Paca" y',
    "prensa?Algunos": "prensa? Algunos",
    "costumbre.Veremos": "costumbre. Veremos",
    "sen- Augusto tarse": "sentarse",
    "Adán Adán solo": "Adán solo",
    "como Manuel ejemplos": "como ejemplos",
    "en el Huerta pasado": "en el pasado",
    "Eje- Claudia cutivo": "Ejecutivo",
    "ma- Sheinbaum nifestaciones": "manifestaciones",
    "O cancelar": "o cancelar",
    "carreteras y Cámara de hospitales": "carreteras y hospitales",
    "Lo que más Diputados han escuchado": "Lo que más han escuchado",
    "desde ejecutar supervisar": "desde ejecutar y supervisar",
    "sismo de\n\n2017": "sismo de 2017",
    "Papaa": "Papa a",
    "traera": "traer a",
    "ámbitoprivado": "ámbito privado",
    "comojefe": "como jefe",
    "cuerposdeseguridad": "cuerpos de seguridad",
    "losjesuitasJavier": "los jesuitas Javier",
    "Camposy": "Campos y",
    "Moraen": "Mora en",
    "Ylafalta": "Y la falta",
    "desolidaridadde": "de solidaridad de",
    "laviolenciacontra": "la violencia contra",
    "enumerarmás": "enumerar más",
    "HéctorMario": "Héctor Mario",
    "aRadio": "a Radio",
    "prontolo": "pronto lo",
    "estéaquí": "esté aquí",
    "tomancuerpo": "toman cuerpo",
    "JorgeRomero": "Jorge Romero",
    "dejuniode": "de junio de",
    "Lasgestiones": "Las gestiones",
    "llevamuyavanzadas": "lleva muy avanzadas",
    "lasnegociaciones": "las negociaciones",
    "MCpara": "MC para",
    "pulverizarel": "pulverizar el",
    "votoopositor": "voto opositor",
    "Yen ": "Y en ",
    "llegara": "llegar a",
    "conazules": "con azules",
    "padreyRicardo": "padre y Ricardo",
    "habráotros": "habrá otros",
    "GUERRATLAXCALTECA": "GUERRA TLAXCALTECA",
    "Apropósitode": "A propósito de",
    "SánchezAnaya": "Sánchez Anaya",
    "deprácticas": "de prácticas",
    "losefectos": "los efectos",
    "operadorespara": "operadores para",
    "decamiones": "de camiones",
    "BAJOSOSPECHA": "BAJO SOSPECHA",
    "TELÃ‰FONOROJO": "TELÃ‰FONO ROJO",
    "4T.Por": "4T. Por",
    "cualquierforma": "cualquier forma",
    "polÃ­ticay": "polÃ­tica y",
    "elsegundo": "el segundo",
    "ladirigencianacional": "la dirigencia nacional",
    "deAriadna": "de Ariadna",
    'partido."Â¿Lesmolesta': 'partido. "Â¿Les molesta',
    "mujero": "mujer o",
    "aintimidar": "a intimidar",
    "morenista.AhÃ­": "morenista. AhÃ­",
    "mejorconocida": "mejor conocida",
    "responsabilidadcon": "responsabilidad con",
    "liderazgo de tu": "liderazgo y de tu",
    "futuro.Estoy": "futuro. Estoy",
    "coordinaciÃ³ny": "coordinaciÃ³n y",
    "familiasmexicanas": "familias mexicanas",
    "deChihuahua": "de Chihuahua",
    "MaruCampos": "Maru Campos",
    "mandatariosestatales": "mandatarios estatales",
    "estadoscuando": "estados cuando",
    "posicionescomunes": "posiciones comunes",
    "paÃ­s.Pendientes": "paÃ­s. Pendientes",
    "pocostuvieron": "pocos tuvieron",
    "laoportunidadde": "la oportunidad de",
    "elestilo el": "el estilo y el",
    "lagobernadora": "la gobernadora",
    "rumboa": "rumbo a",
    "eltema": "el tema",
    "tipocama": "tipo cama",
    "ybebidasgourmet": "y bebidas gourmet",
    "luzcuando": "luz cuando",
    "parecenrelato": "parecen relato",
    "recordaraque": "recordara que",
    "2024fuevista": "2024 fue vista",
    "Nayeli SalvatoriyGracePalomares": "Nayeli Salvatori y Grace Palomares",
    "seconvirtieron": "se convirtieron",
    "pÃºblicopor": "pÃºblico por",
    "el queabordaron": "el que abordaron",
    "lavejez": "la vejez",
    "quedijeron": "que dijeron",
    "yfueradel": "y fuera del",
    "Sheinbaumse": "Sheinbaum se",
    "aPalomaresabrir": "a Palomares abrir",
    "susjÃ³venes": "sus jÃ³venes",
    "Diputadoscomience": "Diputados comience",
    "laFederaciÃ³n": "la FederaciÃ³n",
    "(PEF)del": "(PEF) del",
    "cadaperiodo": "cada periodo",
    "yorganismos": "y organismos",
    "partidajusta": "partida justa",
    "anteproyecto-36": "anteproyecto- 36",
    "seremarcÃ³": "se remarcÃ³",
    "solicitudestÃ¡": "solicitud estÃ¡",
    "primerintento": "primer intento",
    "dadotanto": "dado tanto",
    "parajustificarlos": "para justificar los",
    "lacÃºpula": "la cÃºpula",
    "violando": "violando",
    "decampaÃ±a": "de campaÃ±a",
    "quesimplemente": "que simplemente",
    'al"activismo': 'al "activismo',
    'territorial"que': 'territorial" que',
    "Zavalay": "Zavala y",
    "anticipados.SegÃºn": "anticipados. SegÃºn",
    "odeberÃ­aserinformar": "o deberÃ­a ser informar",
    "dondesolo": "donde solo",
    "audienciasy": "audiencias y",
    "Reuters elestudio": "Reuters el estudio",
    "mÃ¡sambicioso": "mÃ¡s ambicioso",
    "consumo informatidocumenta": "consumo informativo documenta",
    "partedel": "parte del",
    "tiempo.En": "tiempo. En",
    "MÃ©xico erosiÃ³n": "MÃ©xico la erosiÃ³n",
    "cayÃ³al349": "cayÃ³ al 34%",
    "Aestose": "A esto se",
    "yque": "y que",
    "39%ya": "39% ya",
    "fluencers con nosotros": "influencers antes que con nosotros",
    "elhartazgo": "el hartazgo",
    "yolvidamos": "y olvidamos",
    "sueÃ±os control": "sueÃ±os de control y",
    "radicales les": "radicales les",
    "verun": "ver un",
    "venezolana la": "venezolana o la",
    "parareducir": "para reducir",
    "contrariada: reclamar": "contrariada a reclamar",
    "censura de quien": "censura de quien",
    "cÃ­rculorojo": "cÃ­rculo rojo",
    "Volvamosa": "Volvamos a",
    "explicarpor": "explicar por",
    "quÃ©es": "quÃ© es",
    "volvamos: trabajar": "volvamos a trabajar",
    "gentey": "gente y",
    "lasociedad": "la sociedad",
    "apagasolo": "apaga solo",
}


class PeriodismoCorrectionEngine(GenericCorrectionEngine):
    """Motor de correccion para columnas y periodismo politico."""

    id = "periodismo"
    label = "Periodismo"
    description = "Diccionario de artefactos tipicos de columnas periodisticas."

    def correct_block(self, text: str) -> str:
        text = repair_missing_drop_capital(text)
        text = apply_replacements(text, PERIODISMO_REPLACEMENTS)
        return split_glued_uppercase_words(text)

    def correct_document(self, text: str) -> str:
        text = clean_document_text(text)
        text = apply_replacements(text, PERIODISMO_REPLACEMENTS)
        return split_glued_uppercase_words(text)


register_engine(PeriodismoCorrectionEngine())
